package com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.sgm.dms.fol.invoice.wsclient.commonheader.SGMCommonHeaderType;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2016-06-12T10:03:16.755+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://ws.agent.service.dms.sgm.com/", name = "ClaimOperationWebService")
@XmlSeeAlso({com.sgm.dms.fol.invoice.wsclient.commonerror.ObjectFactory.class, ObjectFactory.class, com.sgm.dms.fol.invoice.wsclient.commonheader.ObjectFactory.class})
public interface ClaimOperationWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSubmitToReject", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToReject")
    @WebMethod
    @ResponseWrapper(localName = "changeSubmitToRejectResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToRejectResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationResultVO changeSubmitToReject(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeInvoiceToPayment", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeInvoiceToPayment")
    @WebMethod
    @ResponseWrapper(localName = "changeInvoiceToPaymentResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeInvoiceToPaymentResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationResultVO changeInvoiceToPayment(
    		@WebParam(partName = "header", name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1")
            SGMCommonHeaderType header,@WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeInvoiceToPaymentCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeInvoiceToPaymentCompensation")
    @WebMethod
    @ResponseWrapper(localName = "changeInvoiceToPaymentCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeInvoiceToPaymentCompensationResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationResultVO changeInvoiceToPaymentCompensation(
    		@WebParam(partName = "header", name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1")
            SGMCommonHeaderType header,@WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSubmitToDenyCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToDenyCompensation")
    @WebMethod
    @ResponseWrapper(localName = "changeSubmitToDenyCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToDenyCompensationResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationResultVO changeSubmitToDenyCompensation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSubmitToRejectCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToRejectCompensation")
    @WebMethod
    @ResponseWrapper(localName = "changeSubmitToRejectCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToRejectCompensationResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationResultVO changeSubmitToRejectCompensation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changePaymentToInvoice", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangePaymentToInvoice")
    @WebMethod
    @ResponseWrapper(localName = "changePaymentToInvoiceResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangePaymentToInvoiceResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationResultVO changePaymentToInvoice(
    		@WebParam(partName = "header", name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1")
            SGMCommonHeaderType header,@WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSubmitToDeny", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToDeny")
    @WebMethod
    @ResponseWrapper(localName = "changeSubmitToDenyResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToDenyResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationResultVO changeSubmitToDeny(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSubmitToPayment", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToPayment")
    @WebMethod
    @ResponseWrapper(localName = "changeSubmitToPaymentResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToPaymentResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationResultVO changeSubmitToPayment(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimPaymentOperationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changeSubmitToPaymentCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToPaymentCompensation")
    @WebMethod
    @ResponseWrapper(localName = "changeSubmitToPaymentCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangeSubmitToPaymentCompensationResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationResultVO changeSubmitToPaymentCompensation(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationRequestVO arg0
    ) throws SgmErrorFault;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "changePaymentToInvoiceCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangePaymentToInvoiceCompensation")
    @WebMethod
    @ResponseWrapper(localName = "changePaymentToInvoiceCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", className = "com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ChangePaymentToInvoiceCompensationResponse")
    public com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationResultVO changePaymentToInvoiceCompensation(
    		@WebParam(partName = "header", name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1")
            SGMCommonHeaderType header,@WebParam(name = "arg0", targetNamespace = "")
        com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService.ClaimOperationCompensationRequestVO arg0
    ) throws SgmErrorFault;
}
