
package com.sgm.dms.fol.invoice.wsclient.ClaimOperationWebService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.14
 * 2016-06-12T10:03:16.732+08:00
 * Generated source version: 2.7.14
 */

@WebFault(name = "SGMError", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMError/v1")
public class SgmErrorFault extends Exception {
    
    private com.sgm.dms.fol.invoice.wsclient.commonerror.SGMErrorType sgmError;

    public SgmErrorFault() {
        super();
    }
    
    public SgmErrorFault(String message) {
        super(message);
    }
    
    public SgmErrorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SgmErrorFault(String message, com.sgm.dms.fol.invoice.wsclient.commonerror.SGMErrorType sgmError) {
        super(message);
        this.sgmError = sgmError;
    }

    public SgmErrorFault(String message, com.sgm.dms.fol.invoice.wsclient.commonerror.SGMErrorType sgmError, Throwable cause) {
        super(message, cause);
        this.sgmError = sgmError;
    }

    public com.sgm.dms.fol.invoice.wsclient.commonerror.SGMErrorType getFaultInfo() {
        return this.sgmError;
    }
}
