
package com.sgm.dms.fol.bonus.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BonusOperationWebService", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BonusOperationWebService {


    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.bonus.TranformFrznBonusFundResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformFrznBonusFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformFrznBonusFundResponse tranformFrznBonusFund(
        @WebParam(name = "tranformFrznBonusFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformFrznBonusFund body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.bonus.TranformBonusFundCompensationResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformBonusFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformBonusFundCompensationResponse tranformBonusFundCompensation(
        @WebParam(name = "tranformBonusFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformBonusFundCompensation body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.bonus.TranformBonusFundResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformBonusFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformBonusFundResponse tranformBonusFund(
        @WebParam(name = "tranformBonusFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformBonusFund body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.bonus.TranformUnFrznBonusFundResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformUnFrznBonusFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformUnFrznBonusFundResponse tranformUnFrznBonusFund(
        @WebParam(name = "tranformUnFrznBonusFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformUnFrznBonusFund body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.bonus.TranformUnFrznBonusFundCompensationResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformUnFrznBonusFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformUnFrznBonusFundCompensationResponse tranformUnFrznBonusFundCompensation(
        @WebParam(name = "tranformUnFrznBonusFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformUnFrznBonusFundCompensation body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.bonus.TranformFrznBonusFundCompensationResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformFrznBonusFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformFrznBonusFundCompensationResponse tranformFrznBonusFundCompensation(
        @WebParam(name = "tranformFrznBonusFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformFrznBonusFundCompensation body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

}
