
package com.sgm.dms.fol.bonus.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SGMError", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMError/v1")
public class SgmErrorFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SGMErrorType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SgmErrorFault(String message, SGMErrorType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SgmErrorFault(String message, SGMErrorType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.sgm.dms.service.agent.ws.bonus.SGMErrorType
     */
    public SGMErrorType getFaultInfo() {
        return faultInfo;
    }

}
