package com.sgm.dms.fol.invoice.client;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.sgm.dms.fol.common.service.utils.PropertiesUtil;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 2.7.14
 * 2016-06-22T17:50:54.437+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "FOL_SAP_Z_FI_CREATE_DOC_DMS_PT-bindingQSService", 
                  targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/sap/SGM_OSBApps/POL_FOL/FOL_SAP_Z_FI_CREATE_DOC_DMS") 
public class FOLSAPZFICREATEDOCDMSPTBindingQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/SGM_OSBApps/POL_FOL/FOL_SAP_Z_FI_CREATE_DOC_DMS", "FOL_SAP_Z_FI_CREATE_DOC_DMS_PT-bindingQSService");
    public final static QName FOLSAPZFICREATEDOCDMSPTBindingQSPort = new QName("http://xmlns.oracle.com/pcbpel/adapter/sap/SGM_OSBApps/POL_FOL/FOL_SAP_Z_FI_CREATE_DOC_DMS", "FOL_SAP_Z_FI_CREATE_DOC_DMS_PT-bindingQSPort");
    static {
        URL url = null;
        try {
            url = new URL(PropertiesUtil.getServiceURL("sap_generate_claim_invoice_doc_number_url"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FOLSAPZFICREATEDOCDMSPTBindingQSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://esbsvr01.jqdev.saic-gm.com:7005/esb/ws/sap/claim_document/v1?wsdl");
        } catch (IOException e) {
            java.util.logging.Logger.getLogger(FOLSAPZFICREATEDOCDMSPTBindingQSService.class.getName())
            .log(java.util.logging.Level.INFO, 
                    "url地址 {0}获取失败", "sap_generate_claim_invoice_doc_number_url");
        }
        WSDL_LOCATION = url;
    }

    public FOLSAPZFICREATEDOCDMSPTBindingQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FOLSAPZFICREATEDOCDMSPTBindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FOLSAPZFICREATEDOCDMSPTBindingQSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FOLSAPZFICREATEDOCDMSPTBindingQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FOLSAPZFICREATEDOCDMSPTBindingQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FOLSAPZFICREATEDOCDMSPTBindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FOLSAPZFICREATEDOCDMSPT
     */
    @WebEndpoint(name = "FOL_SAP_Z_FI_CREATE_DOC_DMS_PT-bindingQSPort")
    public FOLSAPZFICREATEDOCDMSPT getFOLSAPZFICREATEDOCDMSPTBindingQSPort() {
        return super.getPort(FOLSAPZFICREATEDOCDMSPTBindingQSPort, FOLSAPZFICREATEDOCDMSPT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FOLSAPZFICREATEDOCDMSPT
     */
    @WebEndpoint(name = "FOL_SAP_Z_FI_CREATE_DOC_DMS_PT-bindingQSPort")
    public FOLSAPZFICREATEDOCDMSPT getFOLSAPZFICREATEDOCDMSPTBindingQSPort(WebServiceFeature... features) {
        return super.getPort(FOLSAPZFICREATEDOCDMSPTBindingQSPort, FOLSAPZFICREATEDOCDMSPT.class, features);
    }

}
