package com.sgm.dms.fol.invoice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.sgm.dms.fol.invoice.header.ObjectFactory;
import com.sgm.dms.fol.invoice.header.SGMCommonHeaderType;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2016-06-22T17:50:54.405+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/pcbpel/adapter/sap/SGM_OSBApps/POL_FOL/FOL_SAP_Z_FI_CREATE_DOC_DMS", name = "FOL_SAP_Z_FI_CREATE_DOC_DMS_PT")
@XmlSeeAlso({ObjectFactory.class, com.sgm.dms.fol.invoice.functions.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface FOLSAPZFICREATEDOCDMSPT {

    @WebResult(name = "Z_FI_CREATE_DOC_DMS_RESPONSE", targetNamespace = "urn:sap-com:document:sap:rfc:functions", partName = "parameters")
    @WebMethod(operationName = "Z_FI_CREATE_DOC_DMS", action = "Z_FI_CREATE_DOC_DMS")
    public com.sgm.dms.fol.invoice.functions.ZFICREATEDOCDMSRESPONSE zFICREATEDOCDMS(
    		@WebParam(partName = "header", name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1")
            SGMCommonHeaderType header,@WebParam(partName = "parameters", name = "Z_FI_CREATE_DOC_DMS", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
        com.sgm.dms.fol.invoice.functions.ZFICREATEDOCDMS body
    );
}
