
package com.sgm.dms.fol.reserve.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReserveOperationWebService", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReserveOperationWebService {


    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.TranformUnFrznReserveFundCompensationResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformUnFrznReserveFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformUnFrznReserveFundCompensationResponse tranformUnFrznReserveFundCompensation(
        @WebParam(name = "tranformUnFrznReserveFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformUnFrznReserveFundCompensation body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.TranformFrznReserveFundResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformFrznReserveFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformFrznReserveFundResponse tranformFrznReserveFund(
        @WebParam(name = "tranformFrznReserveFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformFrznReserveFund body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.TranformFrznReserveFundCompensationResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformFrznReserveFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformFrznReserveFundCompensationResponse tranformFrznReserveFundCompensation(
        @WebParam(name = "tranformFrznReserveFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformFrznReserveFundCompensation body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.TranformUnFrznReserveFundResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformUnFrznReserveFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformUnFrznReserveFundResponse tranformUnFrznReserveFund(
        @WebParam(name = "tranformUnFrznReserveFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformUnFrznReserveFund body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.TranformReserveFundResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformReserveFundResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformReserveFundResponse tranformReserveFund(
        @WebParam(name = "tranformReserveFund", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformReserveFund body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

    /**
     * 
     * @param body
     * @param header
     * @return
     *     returns com.sgm.dms.service.agent.ws.TranformReserveFundCompensationResponse
     * @throws SgmErrorFault
     */
    @WebMethod
    @WebResult(name = "tranformReserveFundCompensationResponse", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
    public TranformReserveFundCompensationResponse tranformReserveFundCompensation(
        @WebParam(name = "tranformReserveFundCompensation", targetNamespace = "http://ws.agent.service.dms.sgm.com/", partName = "body")
        TranformReserveFundCompensation body,
        @WebParam(name = "SGMCommonHeader", targetNamespace = "http://www.saic-gm.com/esb/schemas/common/SGMCommonHeader/v1", header = true, mode = WebParam.Mode.INOUT, partName = "header")
        Holder<SGMCommonHeaderType> header)
        throws SgmErrorFault
    ;

}
