
package com.sgm.dms.fol.reserve.client;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.sgm.dms.fol.common.service.utils.PropertiesUtil;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReserveFundService", targetNamespace = "http://ws.agent.service.dms.sgm.com/")
public class ReserveFundService
    extends Service
{

    private final static URL RESERVEFUNDSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVEFUNDSERVICE_EXCEPTION;
    private final static QName RESERVEFUNDSERVICE_QNAME = new QName("http://ws.agent.service.dms.sgm.com/", "ReserveFundService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = new URL(PropertiesUtil.getServiceURL("reserve_fund_service_wsdl_location"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        } catch (IOException e1) {
			e1.printStackTrace();
		}
        RESERVEFUNDSERVICE_WSDL_LOCATION = url;
        RESERVEFUNDSERVICE_EXCEPTION = e;
    }

    public ReserveFundService() {
        super(__getWsdlLocation(), RESERVEFUNDSERVICE_QNAME);
    }

    public ReserveFundService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVEFUNDSERVICE_QNAME, features);
    }

    public ReserveFundService(URL wsdlLocation) {
        super(wsdlLocation, RESERVEFUNDSERVICE_QNAME);
    }

    public ReserveFundService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVEFUNDSERVICE_QNAME, features);
    }

    public ReserveFundService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReserveFundService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReserveOperationWebService
     */
    @WebEndpoint(name = "ReserveFundPort")
    public ReserveOperationWebService getReserveFundPort() {
        return super.getPort(new QName("http://ws.agent.service.dms.sgm.com/", "ReserveFundPort"), ReserveOperationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReserveOperationWebService
     */
    @WebEndpoint(name = "ReserveFundPort")
    public ReserveOperationWebService getReserveFundPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.agent.service.dms.sgm.com/", "ReserveFundPort"), ReserveOperationWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVEFUNDSERVICE_EXCEPTION!= null) {
            throw RESERVEFUNDSERVICE_EXCEPTION;
        }
        return RESERVEFUNDSERVICE_WSDL_LOCATION;
    }

}
